In [1]:
from public_tests import *
from utils import *
from LinearRegression import LinearReg
from LinearRegression import cost_test_obj
from LinearRegression import compute_gradient_obj

from LinearRegressionMulti import LinearRegMulti
from LinearRegressionMulti import cost_test_multi_obj
from LinearRegressionMulti import compute_gradient_multi_obj
import pandas as pd
import numpy as np

from practica01 import *


First Part, Linear Regression
Second Part, Linear Regression Multivariable


In [2]:

# lo mismo que en practica 01 pero para visualizar
#data = pd.read_csv('C:\GITHUB\AAMD\Practica1\Enunciado\games_data.csv', usecols = ['score','user score'])

# lee los datos y los limpia (EJERCICIO 1.1)
x_data = load_data_csv('games_data.csv', 'score', 'user score')

# hace cosas

# display para debug
display(x_data)

(array([9.9, 9.8, 9.8, ..., 1.7, 1.6, 1.1]),
 array([9.1, 7.4, 7.6, ..., 4.3, 1.3, 2. ]))

In [3]:
def load_data_txt(path,x_colum,y_colum):
    data = pd.read_csv(path)
    X = data[x_colum].to_numpy()
    y = data[y_colum].to_numpy()
    return X, y

In [4]:
# EJERCICIO 1 PRUEBAS

# lectura de los ficheros
x_train, y_train = load_data_csv('games_data.csv', 'score', 'user score')

# este no limpia porque esta bien y es un .txt no un csv, no tiene las columnas
#x_train = pd.read_csv('C:\GITHUB\AAMD\Practica1\Enunciado\ex1data1.txt')

#x1 = x_train['score'].to_numpy()
#x2 = x_train['user score'].to_numpy()

#x_train = x1, x2

#y_train = load_data_txt('C:\GITHUB\AAMD\Practica1\Enunciado\ex1data1.txt', 'score', 'user score')

x_train = np.array(x_train)

# prueba de que se leen bien
#display(y_train)
display(x_train)
display(y_train)

array([9.9, 9.8, 9.8, ..., 1.7, 1.6, 1.1])

array([9.1, 7.4, 7.6, ..., 4.3, 1.3, 2. ])

In [5]:
#probando los tests
# hay que modificar los valores w y b para minimizar el coste de la funcion
# pero cuando ejecuto, como da error, me pone que el coste siempre es el mismo
# andtes era 69 y ahora es 21.cosas pero tio que no cambia con nada

# este metodo ya prepara un w y una b asi que lo de arriba es realmente irrelevante
# ! duda -> este metodo vv se puede modificar o como va la cosa
test_cost_one(x_train, y_train)
test_gradient_one(x_train, y_train)

w,b = run_gradient_descent_one(x_train, y_train)
test_gradient_descent_one(x_train, y_train,w,b)

<class 'numpy.float64'>
Cost at initial w (35.841): 35.841
----Compute cost-------
Testing: compute_cost_test
Cost case 1
Case 1 passed!
Cost case 2
Case 2 passed!
Cost case 3
Case 3 passed!
Cost case 4
Case 4 passed!
Cost case 5
Case 5 passed!
All tests passed!
Gradient at initial w, b (similar to)(-50.49855985112268 -6.988606075159124): -50.498559851122586 -6.988606075159082
Gradient at initial w, b (similar to)(-38.700526233641476 -5.369312042261991): -38.7005262336415 -5.369312042261976
----Compute gradient-------
Testing: compute_gradient_test
Using X with shape (4, 1)
Case 1
0.0 0.0
Case 1 passed!
Case 2
Case 2 passed!
All tests passed!
---- Gradient descent--
w,b found by gradient descent (0.8262848855238131 1.0746825556592443): 0.8262848855238131 1.0746825556592443
for score 3.5, we predict user score of (3.97) 3.97
3.96667965499259
Case 1
Case 1 passed!
for score 7.9, we predict user score of (6.86) 6.86
Case 2
6.858676754325936
Case 2 passed!
All tests passed!


In [ ]:
x_train, y_train = load_data_csv_multi('games_data.csv', 'score', 'critics', 'users', 'user score')

#display(x_train)
#display(y_train)

print("ZScore")

X_norm, mu, sigma = zscore_normalize_features(x_train)

#display(X_norm)


#Second Part, Linear Regression Multivariable
print("Second Part, Linear Regression Multivariable")
#TO-DO the main program.
test_cost_multi(X_norm, y_train)
test_gradient_multi(x_train, y_train)
test_gradient_descent_multi(x_train, y_train)

array([[9.900e+00, 2.200e+01, 5.749e+03],
       [9.800e+00, 1.900e+01, 6.470e+02],
       [9.800e+00, 6.400e+01, 3.806e+03],
       ...,
       [1.700e+00, 7.000e+00, 1.290e+02],
       [1.600e+00, 9.000e+00, 5.810e+02],
       [1.100e+00, 8.000e+00, 1.510e+02]])

array([9.1, 7.4, 7.6, ..., 4.3, 1.3, 2. ])

ZScore


array([[-0.08109769, -0.06540216,  7.3633806 ],
       [-0.0812274 , -0.06929361,  0.7453171 ],
       [-0.0812274 , -0.01092183,  4.84301655],
       ...,
       [-0.09173432, -0.08485942,  0.07339298],
       [-0.09186404, -0.08226512,  0.65970515],
       [-0.09251261, -0.08356227,  0.1019303 ]])

Second Part, Linear Regression Multivariable
------------test_cost-----------
All tests passed!
------------test_gradient-----------


AssertionError: Case 1: dj_db is wrong: -5.0217753368997364e-06 != -1.6739251122999121e-06