In [1]:
from public_tests import *
from utils import *
from LinearRegression import LinearReg
from LinearRegression import cost_test_obj
from LinearRegression import compute_gradient_obj

from LinearRegressionMulti import LinearRegMulti
from LinearRegressionMulti import cost_test_multi_obj
from LinearRegressionMulti import compute_gradient_multi_obj
import pandas as pd
import numpy as np

from practica01 import *


First Part, Linear Regression
Second Part, Linear Regression Multivariable


In [2]:

# lo mismo que en practica 01 pero para visualizar
#data = pd.read_csv('C:\GITHUB\AAMD\Practica1\Enunciado\games_data.csv', usecols = ['score','user score'])

# lee los datos y los limpia (EJERCICIO 1.1)
x_data = load_data_csv('games_data.csv', 'score', 'user score')

# hace cosas

# display para debug
display(x_data)

(array([99., 98., 98., ..., 17., 16., 11.], shape=(16658,)),
 array([91., 74., 76., ..., 43., 13., 20.], shape=(16658,)))

In [3]:
def load_data_txt(path,x_colum,y_colum):
    data = pd.read_csv(path)
    X = data[x_colum].to_numpy()
    y = data[y_colum].to_numpy()
    return X, y

In [4]:
# EJERCICIO 1 PRUEBAS

# lectura de los ficheros
x_train, y_train = load_data_csv('games_data.csv', 'score', 'user score')

# este no limpia porque esta bien y es un .txt no un csv, no tiene las columnas
#x_train = pd.read_csv('C:\GITHUB\AAMD\Practica1\Enunciado\ex1data1.txt')

#x1 = x_train['score'].to_numpy()
#x2 = x_train['user score'].to_numpy()

#x_train = x1, x2

#y_train = load_data_txt('C:\GITHUB\AAMD\Practica1\Enunciado\ex1data1.txt', 'score', 'user score')

x_train = np.array(x_train)

# prueba de que se leen bien
#display(y_train)
display(x_train)
display(y_train)

array([99., 98., 98., ..., 17., 16., 11.], shape=(16658,))

array([91., 74., 76., ..., 43., 13., 20.], shape=(16658,))

In [5]:
#probando los tests
# hay que modificar los valores w y b para minimizar el coste de la funcion
# pero cuando ejecuto, como da error, me pone que el coste siempre es el mismo
# andtes era 69 y ahora es 21.cosas pero tio que no cambia con nada

# este metodo ya prepara un w y una b asi que lo de arriba es realmente irrelevante
# ! duda -> este metodo vv se puede modificar o como va la cosa
test_cost_one(x_train, y_train)
#test_gradient_one(x_train, y_train)
#test_gradient_descent_one(x_train, y_train,w,b)

<class 'numpy.float64'>
Cost at initial w (35.841): 2886.215
----Compute cost-------
Testing: compute_cost_test
Cost case 1
Case 1 passed!
Cost case 2
Case 2 passed!
Cost case 3
Case 3 passed!
Cost case 4
Case 4 passed!
Cost case 5
Case 5 passed!
All tests passed!
