In [6]:
from public_tests import *
from utils import *
from LinearRegression import LinearReg
from LinearRegression import cost_test_obj
from LinearRegression import compute_gradient_obj

from LinearRegressionMulti import LinearRegMulti
from LinearRegressionMulti import cost_test_multi_obj
from LinearRegressionMulti import compute_gradient_multi_obj
import pandas as pd
import numpy as np

from practica01 import *


In [7]:

# lo mismo que en practica 01 pero para visualizar
#data = pd.read_csv('C:\GITHUB\AAMD\Practica1\Enunciado\games_data.csv', usecols = ['score','user score'])

# lee los datos y los limpia (EJERCICIO 1.1)
x_data = load_data_csv('C:\GITHUB\AAMD\Practica1\Enunciado\games_data.csv', 'score', 'user score')

# hace cosas

# display para debug
display(x_data)

(array([99., 98., 98., ..., 17., 16., 11.], shape=(16658,)),
 array([91., 74., 76., ..., 43., 13., 20.], shape=(16658,)))

In [8]:
def load_data_txt(path,x_colum,y_colum):
    data = pd.read_csv(path)
    X = data[x_colum].to_numpy()
    y = data[y_colum].to_numpy()
    return X, y

In [9]:
# EJERCICIO 1 PRUEBAS

# lectura de los ficheros
x_train = load_data_csv('C:\GITHUB\AAMD\Practica1\Enunciado\games_data.csv', 'score', 'user score')

# este no limpia porque esta bien y es un .txt no un csv, no tiene las columnas
#x_train = pd.read_csv('C:\GITHUB\AAMD\Practica1\Enunciado\ex1data1.txt')

#x1 = x_train['score'].to_numpy()
#x2 = x_train['user score'].to_numpy()

#x_train = x1, x2

#y_train = load_data_txt('C:\GITHUB\AAMD\Practica1\Enunciado\ex1data1.txt', 'score', 'user score')

x_train = np.array(x_train)

# prueba de que se leen bien
#display(y_train)
display(x_train)

array([[99., 98., 98., ..., 17., 16., 11.],
       [91., 74., 76., ..., 43., 13., 20.]], shape=(2, 16658))

In [ ]:
#probando los tests
lr = LinearReg(x_train, x_train, 1, 2)
y_train = lr.f_w_b(x_train)
lr.y = y_train

test_cost_one(x_train, y_train)
#test_gradient_one(x_train, y_train)
#test_gradient_descent_one(x_train, y_train,w,b)

Gradient at initial w, b (similar to)(-50.49855985112268 -6.988606075159124): (array([[-inf, -inf, -inf, ...,  inf, -inf,  inf],
       [-inf, -inf, -inf, ...,  inf, -inf,  inf]], shape=(2, 16658)), array([[-inf, -inf,  nan, ..., -inf, -inf, -inf],
       [-inf, -inf,  inf, ..., -inf, -inf,  inf]], shape=(2, 16658))) (array([[-inf, -inf, -inf, ...,  inf, -inf,  inf],
       [-inf, -inf, -inf, ...,  inf, -inf,  inf]], shape=(2, 16658)), array([[-inf, -inf,  nan, ..., -inf, -inf, -inf],
       [-inf, -inf,  inf, ..., -inf, -inf,  inf]], shape=(2, 16658)))
Gradient at initial w, b (similar to)(-38.700526233641476 -5.369312042261991): (array([[ -40., -120., -110., ...,  130.,  -15.,   45.],
       [ -40., -120., -110., ...,  130.,  -15.,   45.]], shape=(2, 16658)), array([[ -5. ,  -2.5,   0. , ...,  -2.5, -15. , -25. ],
       [-85. , -37.5,  27.5, ..., -15. , -57.5,  35. ]], shape=(2, 16658))) (array([[ -40., -120., -110., ...,  130.,  -15.,   45.],
       [ -40., -120., -110., ...,  130.

C:\Users\ineso\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_function_base_impl.py:1307: RuntimeWarning: divide by zero encountered in divide
  out[tuple(slice1)] = (f[tuple(slice2)] - f[tuple(slice3)]) / dx_0
C:\Users\ineso\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_function_base_impl.py:1307: RuntimeWarning: invalid value encountered in divide
  out[tuple(slice1)] = (f[tuple(slice2)] - f[tuple(slice3)]) / dx_0
C:\Users\ineso\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_function_base_impl.py:1314: RuntimeWarning: divide by zero encountered in divide
  out[tuple(slice1)] = (f[tuple(slice2)] - f[tuple(slice3)]) / dx_n
C:\Users\ineso\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\loca

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()