In [2]:
from public_tests import *
from utils import *
from LinearRegression import LinearReg
from LinearRegression import cost_test_obj
from LinearRegression import compute_gradient_obj

from LinearRegressionMulti import LinearRegMulti
from LinearRegressionMulti import cost_test_multi_obj
from LinearRegressionMulti import compute_gradient_multi_obj
import pandas as pd
import numpy as np

from practica01 import *


First Part, Linear Regression
Second Part, Linear Regression Multivariable


In [3]:

# lo mismo que en practica 01 pero para visualizar
#data = pd.read_csv('C:\GITHUB\AAMD\Practica1\Enunciado\games_data.csv', usecols = ['score','user score'])

# lee los datos y los limpia (EJERCICIO 1.1)
data = load_data_csv('C:\GITHUB\AAMD\Practica1\Enunciado\games_data.csv', 'score', 'user score')

# hace cosas

# display para debug
display(data)

(array([99., 98., 98., ..., 17., 16., 11.], shape=(16658,)),
 array([91., 74., 76., ..., 43., 13., 20.], shape=(16658,)))

In [20]:
def load_data_txt(path,x_colum,y_colum):
    data = pd.read_csv(path)
    X = data[x_colum].to_numpy()
    y = data[y_colum].to_numpy()
    return X, y

In [21]:
# EJERCICIO 1 PRUEBAS

# lectura de los ficheros
y_train = load_data_csv('C:\GITHUB\AAMD\Practica1\Enunciado\games_data.csv', 'score', 'user score')

# este no limpia porque esta bien y es un .txt no un csv, no tiene las columnas
#x_train = pd.read_csv('C:\GITHUB\AAMD\Practica1\Enunciado\ex1data1.txt')

#x1 = x_train['score'].to_numpy()
#x2 = x_train['user score'].to_numpy()

#x_train = x1, x2

load_data_txt('C:\GITHUB\AAMD\Practica1\Enunciado\ex1data1.txt', 'score', 'user score')

# prueba de que se leen bien
display(y_train)
display(x_train)

(array([99., 98., 98., ..., 17., 16., 11.], shape=(16658,)),
 array([91., 74., 76., ..., 43., 13., 20.], shape=(16658,)))

(array([ 6.1101,  5.5277,  8.5186,  7.0032,  5.9598,  8.5829,  7.5764,
         8.57  ,  6.4862,  5.0546,  5.7107, 14.164 ,  5.734 ,  8.4084,
         5.6407,  5.3794,  6.3654,  5.1301,  6.4296,  7.0708,  6.1891,
        20.27  ,  5.4901,  6.3261,  5.5649, 18.945 , 12.828 , 10.957 ,
        13.176 , 22.203 ,  5.2524,  6.5894,  9.2482,  5.8918,  8.2111,
         7.9334,  8.0959,  5.6063, 12.836 ,  6.3534,  5.4069,  6.8825,
        11.708 ,  5.7737,  7.8247,  7.0931,  5.0702,  5.8014, 11.7   ,
         5.5416,  7.5402,  5.3077,  7.4239,  7.6031,  6.3328,  6.3589,
         6.2742,  5.6397,  9.3102,  9.4536,  8.8254,  5.1793, 21.279 ,
        14.908 , 18.959 ,  7.2182,  8.2951, 10.236 ,  5.4994, 20.341 ,
        10.136 ,  7.3345,  6.0062,  7.2259,  5.0269,  6.5479,  7.5386,
         5.0365, 10.274 ,  5.1077,  5.7292,  5.1884,  6.3557,  9.7687,
         6.5159,  8.5172,  9.1802,  6.002 ,  5.5504,  5.0594,  5.7077,
         7.6366,  5.8777,  5.3054,  9.2934, 14.594 ,  5.0369]),
 array([17.09

In [ ]:
#probando los tests

#test_cost_one(x_train, y_train)
#test_gradient_one(x_train, y_train)
#test_gradient_descent_one(x_train, y_train,w,b)

TypeError: unsupported operand type(s) for -: 'tuple' and 'tuple'